<?xml version="1.0" encoding="UTF-8"?>
<list word="fold.v">
<s path="[MASC]/data/written/1399.anc" start="11216" end="11222" sStart="11180" offset="36" sid="r9.fold.v.0002" wn="">Contoured metallic parts glided and folded out over me, emerging from the wall and pushing me back in with them.</s>
<s path="[MASC]/data/written/1400.anc" start="9162" end="9168" sStart="9150" offset="12" sid="r9.fold.v.0003" wn="">The android folded his arms, utterly stumped.</s>
<s path="[MASC]/data/written/1401.anc" start="20819" end="20826" sStart="20787" offset="32" sid="r9.fold.v.0004" wn="">Sandra shrank down the hallway, folding her shoulders over her torso.</s>
<s path="[MASC]/data/written/1403.anc" start="2749" end="2756" sStart="2678" offset="71" sid="r9.fold.v.0005" wn="">It functioned like a Spinning Wheel, twisting fibers of time space and folding them on a molecular level to create what he called “Newmatter.</s>
<s path="[MASC]/data/written/1471-2091-2-9.anc" start="2650" end="2657" sStart="2602" offset="48" sid="r9.fold.v.0006" wn="">Mutation of W187A in ACR3 affected CD39 folding and translocation, while mutation of W459A in ACR5 increased ATPase activity but diminished ADPase activity [ 14 ] .</s>
<s path="[MASC]/data/written/CUP1.anc" start="2438" end="2445" sStart="2394" offset="33" sid="r9.fold.v.0009" wn="">Surface deformation by faulting, folding, and lateral tilting.</s>
<s path="[MASC]/data/written/CUP1.anc" start="3233" end="3240" sStart="3221" offset="12" sid="r9.fold.v.0010" wn="">The type of folding (Figure 2.1) will affect a river similar to the various types of faulting, but changes will probably be less abrupt.</s>
<s path="[MASC]/data/written/CUP1.anc" start="4539" end="4546" sStart="4467" offset="72" sid="r9.fold.v.0011" wn="">While fault displacements are obvious, movements of the land surface by folding can be slow.</s>
<s path="[MASC]/data/written/hotel-california.anc" start="7768" end="7774" sStart="7721" offset="47" sid="r9.fold.v.0012" wn="">The plate, by the way, was already loaded with folded pieces of smoked pink fish, paprika-dusted deviled eggs, toothpicks stabbed through green vegetables and slices of cheese, and balls of meat smothered in a tomato-based sauce.</s>
<s path="[MASC]/data/written/hotel-california.anc" start="20950" end="20956" sStart="20916" offset="34" sid="r9.fold.v.0013" wn="">Ray, he looked down at his hands, folded together in his lap, fingers interlaced.</s>
<s path="[MASC]/data/written/lists-046-12122969.anc" start="4036" end="4043" sStart="4013" offset="23" sid="r9.fold.v.0014" wn="">We discussed ideas for folding and unfolding expressions.</s>
<s path="[MASC]/data/written/lists-046-12122969.anc" start="4213" end="4219" sStart="4208" offset="5" sid="r9.fold.v.0015" wn="">When folded the given name would be shown in place of the subexpression itself.</s>
<s path="[MASC]/data/written/lists-046-12133410.anc" start="1006" end="1013" sStart="1043" offset="0" sid="r9.fold.v.0016" wn="">AsTeR also implemented a fairly straight-forward naming algorithm for giving meaningful names to sub-expressions e.g. &quot;lower constraint 1&quot; and denominator 3&quot; etc.</s>
<s path="[MASC]/data/written/lists-046-12133410.anc" start="1519" end="1526" sStart="1380" offset="154" sid="r9.fold.v.0017" wn="">However, even without the intelligence to recognize two semantically equivalent instances of a subexpression, &quot;variable substitution&quot; or &quot;folding&quot; as Dave refers to it in his minutes is *really* useful for speech and I suspect it would be very useful for small visual displays.</s>
<s path="[MASC]/data/written/Nathans_Bylichka.anc" start="1836" end="1843" sStart="1807" offset="29" sid="r9.fold.v.0018" wn="">“It’s from Mitch,” she said, folding up the phone.</s>
<s path="[OANC]/data/written_1/journal/slate/9/Article247_3283.anc" start="2557" end="2563" sStart="2487" offset="70" sid="r9.fold.v.0421" wn="">Waldrop, the former editor of the Washington Times-Herald , which was folded into the Washington Post in 1954, died two years ago at age 92.</s>
<s path="[OANC]/data/written_1/journal/slate/10/Article247_3315.anc" start="401" end="405" sStart="313" offset="88" sid="r9.fold.v.0678" wn="">On average, every third person is reading a newspaper: There are the contortionists who fold the ever-expanding Times into readable wedges, the tabloid readers (whose papers are enviably scaled for reading in motion), and a scattering of people clutching Spanish or Asian papers.</s>
  
<s path="[OANC]/data/written_1/journal/slate/12/Article247_3563.anc" start="613" end="617" sStart="395" offset="218" sid="r9.fold.v.0909" wn="">FCC regulations may require the new Viacom to sell a few of its TV stations--because there's a rule saying one company can't own stations that serve more than 35 percent of the United States--and to either spin off or fold in the still-struggling UPN.</s>
<s path="[OANC]/data/written_1/journal/slate/14/Article247_3763.anc" start="199" end="205" sStart="145" offset="54" sid="r9.fold.v.0425" wn="">I think it's being a little hard on Miramax to say it folded on Dogma; it kept its commitments to the film and to Disney by buying it (film, not Disney) back and arranging to distribute it independently.</s>
<s path="[OANC]/data/written_1/journal/slate/28/ArticleIP_1660.anc" start="2074" end="2081" sStart="1996" offset="78" sid="r9.fold.v.0993" wn="">Iraq absorbed 88,000 tons of bombs during the 43 days of the Gulf War without folding or replacing Saddam, noted several pundits, including Tim Russert on NBC's Meet the Press . Saddam's bio-chem arsenal was surely bunkered beyond the reach of U.S. bombs, they concluded.</s>
<s path="[OANC]/data/written_1/journal/slate/32/ArticleIP_2075.anc" start="8657" end="8663" sStart="8484" offset="173" sid="r9.fold.v.0756" wn="">This theory singles out current Executive Editor Downie for abuse, but complacency took root as early as 1981, when the Post 's cross-town competitor, the Washington Star , folded, allowing the fat beast to diddle all it wanted without paying a price.</s>
  
<s path="[OANC]/data/written_1/journal/slate/33/ArticleIP_2185.anc" start="2936" end="2942" sStart="2830" offset="106" sid="r9.fold.v.0066" wn="">At best, paper's materiality creates an unjustified impression of trustworthiness; at worst, paper can be folded into an airplane that can poke someone's eye out.</s>
<s path="[OANC]/data/written_1/journal/slate/34/ArticleIP_2257.anc" start="4483" end="4489" sStart="4450" offset="33" sid="r9.fold.v.0740" wn="">Another part is that the CDA was folded into the telecommunications bill, an acre of legislation that reorganizes one-seventh of the nation's economy.</s>
  
<s path="[OANC]/data/written_1/journal/slate/36/ArticleIP_2482.anc" start="3027" end="3033" sStart="3008" offset="19" sid="r9.fold.v.0410" wn="">After her marriage folded, Joyce started merchandising ghoulish, oddball dating stories, some of them prompted by this personal ad she placed in Boston magazine: &quot;The truth is I'm gorgeous, slender, talented, and passionate.</s>
  
<s path="[OANC]/data/written_1/journal/slate/42/ArticleIP_3105.anc" start="5213" end="5217" sStart="5166" offset="47" sid="r9.fold.v.0174" wn="">Women wearing short skirts and smart shoes who fold a modish scarf on their heads in the ancient veil-like manner are trying to have it both ways.</s>
  
<s path="[OANC]/data/written_1/journal/slate/48/ArticleIP_6694.anc" start="3504" end="3510" sStart="3445" offset="59" sid="r9.fold.v.0844" wn="">In the back of the speakers is a 7 foot tube that has been folded into a thin, tight maze to fit inside the radio box.</s>
  
<s path="[OANC]/data/written_1/journal/slate/48/ArticleIP_6882.anc" start="2533" end="2539" sStart="2366" offset="167" sid="r9.fold.v.0564" wn="">I used to keep my balance, the edges were eaten,the lead was grey, the green eraser was worn down to the metal, and I had a spiral notebook I kept for emotions, and I folded my money.</s>
  
<s path="[OANC]/data/written_1/journal/slate/49/ArticleIP_19300.anc" start="5083" end="5087" sStart="4968" offset="115" sid="r9.fold.v.0049" wn="">Q: Isn't this change a sign that you're getting desperate, that Microsoft is losing interest, that you're about to fold, that the end is nigh, strange and dreadful diseases are about to ravage the population, the stock market is going to tank, Linda Tripp will get her own TV talk show, and so on?</s>
<s path="[OANC]/data/written_1/journal/slate/50/ArticleIP_29453.anc" start="6063" end="6069" sStart="6017" offset="46" sid="r9.fold.v.0584" wn="">Democrats, unwilling to take another beating, folded, voting unanimously for the bill in full committee.</s>
  
<s path="[OANC]/data/written_1/journal/slate/51/ArticleIP_36654.anc" start="2382" end="2388" sStart="2263" offset="119" sid="r9.fold.v.0881" wn="">I've always favored the alternative plan--small, unmanned probes, along with a gigantic annual bonfire of $1,000 bills folded into origami cranes.</s>
<s path="[OANC]/data/written_1/journal/slate/51/ArticleIP_36993.anc" start="1670" end="1677" sStart="1434" offset="256" sid="r9.fold.v.0406" wn="">You could not imagine better comic material than her ideas of &quot;living&quot;: the &quot;midnight omelet dinner for 1,000&quot;; the fruit baskets the size of a Chevy; the advice (in this month's magazine) to make your own envelopes out of wood veneer, folding them with a bone knife.</s>
  
<s path="[OANC]/data/written_1/journal/verbatim/VOL23_4.anc" start="63940" end="63946" sStart="63749" offset="191" sid="r9.fold.v.0461" wn="">Winchester invents some luscious women: young, chocolate-skinned, giggling naked girls with sleek wet bodies and rosebud nipples and long hair and coltish legs with scarlet and purple petals folded behind their ears, who play in the white Indian Ocean surf and who run, quite without shame, along the cool wet sands on their way back home (40).</s>
<s path="[OANC]/data/written_1/letters/icic/602CZL282.anc" start="534" end="541" sStart="440" offset="94" sid="r9.fold.v.0737" wn="">The landmark acquisition in December of 75 rare and important hanging scrolls and folding screens is evidence of the commitment to build the IMA's permanent collection of world art.</s>
<s path="[OANC]/data/written_2/technical/biomed/1471-2091-2-9.anc" start="2650" end="2657" sStart="2393" offset="257" sid="r9.fold.v.0097" wn="">E174 in ACR3 and S218 in ACR4 are required for catalytic function [ 12 ] . Substitution of H59 in ACR1 converted CD39 into an ADPase in a quaternary structure dependent manner [ 13 ] . Mutation of W187A in ACR3 affected CD39 folding and translocation, while mutation of W459A in ACR5 increased ATPase activity but diminished ADPase activity [ 14 ] . Mutations of D62 and G64 of ACR1 and D219 and G221 of ACR4 demonstrated that the nucleotide phosphate binding domains of NTPDases are similar to those present in the actin/heat shock protein/sugar kinase superfamily [ 15 ] . These results suggest that the conserved residues of the ACR1 to 5 regions are involved in the catalytic mechanism of CD39.</s>
<s path="[OANC]/data/written_2/technical/biomed/1471-2091-3-13.anc" start="1260" end="1266" sStart="1087" offset="173" sid="r9.fold.v.0397" wn="">The three tetracysteine motifs do not form a stably folded structure on its own, but when combined with the 14 kDa C-terminal domain, forms a stably folded 268 amino acid DNA binding domain (ZD domain) that has higher affinity for single-stranded DNA than the 121 amino acid 14 kDa C-terminal region by itself [ 6 ] . Recent sequence and structural analysis suggests that the 14 kDa domain is evolutionarily related to the three tetracysteine motifs and belongs to the zinc ribbon family [ 7 ] . The ZD domain in E. coli topoisomerase I probably evolved from a domain that binds five Zn(II) originally.</s>
<s path="[OANC]/data/written_2/technical/biomed/1471-2148-3-3.anc" start="9012" end="9019" sStart="8929" offset="83" sid="r9.fold.v.0548" wn="">In this paper, we focus on a fairly simple system (RNA secondary structure folding), which avoids the first explanation above because of complete information, and avoids the second and third explanations because there is only a single gene with dichotomous fitness (0 or 1) in the system.</s>
  
<s path="[OANC]/data/written_2/technical/biomed/1471-2148-3-3.anc" start="27150" end="27154" sStart="27112" offset="38" sid="r9.fold.v.0448" wn="">Only a very small number of sequences fold into any given rare structure.</s>
  
<s path="[OANC]/data/written_2/technical/biomed/1471-2148-3-3.anc" start="28343" end="28347" sStart="28228" offset="115" sid="r9.fold.v.0020" wn="">Percolation means that it is possible to find two sequences with almost no sequence identity which fold into the same structure, and which are connected by a path of mutant sequences that also fold into the same structure.</s>
<s path="[OANC]/data/written_2/technical/biomed/1471-2148-3-3.anc" start="28445" end="28449" sStart="28228" offset="217" sid="r9.fold.v.0628" wn="">Percolation means that it is possible to find two sequences with almost no sequence identity which fold into the same structure, and which are connected by a path of mutant sequences that also fold into the same structure.</s>
  
<s path="[OANC]/data/written_2/technical/biomed/1471-2148-3-3.anc" start="29664" end="29668" sStart="29645" offset="19" sid="r9.fold.v.0168" wn="">Two sequences that fold into the same structure may bind to a receptor with different efficiencies, and a sequence that folds into a slightly different structure may also bind to the receptor, albeit less efficiently.</s>
  
<s path="[OANC]/data/written_2/technical/biomed/1471-2148-3-3.anc" start="32419" end="32426" sStart="32392" offset="27" sid="r9.fold.v.0325" wn="">Several studies of protein folding in silico indicate that widespread neutral networks exist, comparable to the situation for RNA sequences [ 39 49 50 ] . Moreover, decay functions similar to the function w ( d ) studied here have been measured in vitro [ 51 52 ] by making fitness a binary variable (e.g.</s>
<s path="[OANC]/data/written_2/technical/biomed/1471-2148-3-3.anc" start="37014" end="37020" sStart="37004" offset="10" sid="r9.fold.v.0605" wn="">..,8 that folded into the same structure, by calculating the secondary structure of up to 10 6mutant sequences at each Hamming distance.</s>
<s path="[OANC]/data/written_2/technical/biomed/1471-2156-4-6.anc" start="2406" end="2410" sStart="2094" offset="312" sid="r9.fold.v.0741" wn="">For instance, they are dispensable for DNA damage-dependent activation of the Rad26/Rad3-kinase complex [ 18 ] , but are required for the Rad3-dependent phosphorylation of Chk1 [ 23 ] . Structural predictions of Hus1, Rad1 and Rad9 have led to the proposal that all three fold similarly to the subunits of Proliferating Cell Nuclear Antigen (PCNA) [ 24 25 26 ] . Consistent with these predictions, PCNA exists as a homotrimer [ 27 ] while Hus1, Rad1 and Rad9 all interact and possibly form a heterotrimer [ 25 28 ] . In addition, Rad17 has sequence similarity and physical interactions with subunits of Replication Factor C (RFC) [ 29 30 ] . Based on the RFC-PCNA paradigm, the Rad17-RFC complex may load the PCNA-like Rad9-Rad1-Hus1 (9-1-1) complex onto genomic lesions discovered by the Rad26/Rad3 complex.</s>
<s path="[OANC]/data/written_2/technical/biomed/1471-2164-3-18.anc" start="22529" end="22536" sStart="21686" offset="843" sid="r9.fold.v.0134" wn="">One possibility is that the MIDAS site serves to attach protein ligands through a mechanism involving participation of a glutamate or aspartate residue on the ligand in the coordination of a Mg 2+ion at the MIDAS site of midasin, in a manner similar to that by which the MIDAS site in integrin I-domains appears to mediate attachment of collagen through the glutamate in the GFOGER binding motif [ 36 ] . Interestingly, the related RGE ligand-binding motif [ 41 ] occurs in a conserved region of the midasin AAA-domain (yeast, residues 1835-1838), as well as in the AAA-domain of Mg chelatases [ 32 ] . The presence of this consensus binding motif in the AAA domain raises the possibility of the midasin molecule folding back onto itself, with the M-domain becoming attached to one face of the AAA domain and perhaps regulating access to its central chamber, in a manner analogous to that in which the 19S proteasome regulator, also an AAA protein, controls access to the central proteolytic chamber of the proteasome [ 42 ] .</s>
  
<s path="[OANC]/data/written_2/technical/biomed/1471-2164-4-28.anc" start="8064" end="8068" sStart="7882" offset="185" sid="r9.fold.v.0677" wn="">In contrast, with regular microarray, 227 and 244 of 10,000 genes were detected at 2-4 fold up- and down-regulated, respectively; 10 and 30 genes at &gt;4 fold up- and down-regulated, respectively.</s>
<s path="[OANC]/data/written_2/technical/biomed/1471-2164-4-28.anc" start="8605" end="8609" sStart="8541" offset="67" sid="r9.fold.v.0185" wn="">However, with ADGE microarray, there were 63 genes &gt;4 fold up-regulated, 220 genes 2-4 fold up-regulated, 92 genes 2-4 fold down-regulated and 14 genes &gt;4 down-regulated.</s>
<s path="[OANC]/data/written_2/technical/biomed/1471-2180-2-1.anc" start="23015" end="23022" sStart="23009" offset="6" sid="r9.fold.v.0781" wn="">fiber folding during morphogenesis [ 3 ]</s>
<s path="[OANC]/data/written_2/technical/biomed/1471-2180-2-16.anc" start="8158" end="8165" sStart="7999" offset="159" sid="r9.fold.v.0772" wn="">Initially, alanine-scanning mutagenesis was used for this study as alanine substitutions are generally thought to minimally effect protein folding [ 27 ] . Sequence conservation from the alignment of LcrG with the</s>
  
<s path="[OANC]/data/written_2/technical/biomed/1471-2180-2-32.anc" start="5623" end="5627" sStart="5478" offset="145" sid="r9.fold.v.0742" wn="">It has been suggested that perhaps cytoplasmic proteins are not exported in prl suppressor strains because they fold rapidly and escape recognition by SecB, while secretory proteins, even those lacking a signal sequence, fold more slowly, allowing time for SecB recognition and binding [ 5 13 ] . SecB binds to a variety of unfolded proteins in vitro [ 24 25 ] , although binding appears to be more selective in vivo [ 26 ] . This selectivity may be based on the slower folding characteristics of secretory proteins.</s>
  
<s path="[OANC]/data/written_2/technical/biomed/1471-2180-2-32.anc" start="5748" end="5752" sStart="5478" offset="270" sid="r9.fold.v.0416" wn="">It has been suggested that perhaps cytoplasmic proteins are not exported in prl suppressor strains because they fold rapidly and escape recognition by SecB, while secretory proteins, even those lacking a signal sequence, fold more slowly, allowing time for SecB recognition and binding [ 5 13 ] . SecB binds to a variety of unfolded proteins in vitro [ 24 25 ] , although binding appears to be more selective in vivo [ 26 ] . This selectivity may be based on the slower folding characteristics of secretory proteins.</s>
  
<s path="[OANC]/data/written_2/technical/biomed/1471-2199-2-6.anc" start="8941" end="8945" sStart="8910" offset="31" sid="r9.fold.v.0490" wn="">The ability of coat protein to fold correctly is sometimes sensitive to amino acid substitution.</s>
  
<s path="[OANC]/data/written_2/technical/biomed/1471-2202-3-7.anc" start="14678" end="14682" sStart="14644" offset="34" sid="r9.fold.v.0608" wn="">The discovery that GFP will still fold and form a fluorophore when placed virtually anywhere in another coding region suggests that the limiting step in the process is whether the target protein it is inserted into folds and functions correctly.</s>
  
<s path="[OANC]/data/written_2/technical/biomed/1471-2202-3-16.anc" start="15346" end="15350" sStart="15190" offset="156" sid="r9.fold.v.0023" wn="">If genes with a mean intensity expression level of less than 1000 are removed from the analysis (top five rows, Table 2), and the array fold changes of the remaining 19 genes are plotted against the slot blot fold changes, a very strong correlation is evident (linear regression r 2= 0.8567) (Figure 2E).</s>
<s path="[OANC]/data/written_2/technical/biomed/1471-2288-2-11.anc" start="13637" end="13643" sStart="13592" offset="45" sid="r9.fold.v.0484" wn="">The effect of later switching is folded into the interpretation.</s>
  
<s path="[OANC]/data/written_2/technical/biomed/1472-6807-2-3.anc" start="1304" end="1308" sStart="1167" offset="137" sid="r9.fold.v.0789" wn="">There are three primary categories of methods for predicting protein structure from sequence: comparative modelling, fold recognition, and ab initio prediction.</s>
<s path="[OANC]/data/written_2/technical/biomed/1472-6807-3-2.anc" start="7288" end="7292" sStart="7264" offset="24" sid="r9.fold.v.0126" wn="">The two flaps fold over the inhibitor to form a tunnel-shaped active site and are held in this close position by hydrogen bonding from Ile50 and Ile50' NH groups of the enzyme to a water molecule, which in turn is hydrogen bonded to the P2 and P1' CO groups of the inhibitor [ 24 ] . The bonding stabilizes the flaps in a closed position and inhibits the activities of the enzyme.</s>
  
<s path="[OANC]/data/written_2/technical/biomed/ar409.anc" start="11092" end="11096" sStart="11023" offset="69" sid="r9.fold.v.0505" wn="">Centrifugal concentration of viral supernatant by 10- to 100-fold significantly increased the efficiency of viral transduction, with 50% or more of FLS expressing EGFP in several independent experiments using FLS lines from separate donors.</s>
<s path="[OANC]/data/written_2/technical/biomed/gb-2001-2-6-research0021.anc" start="17595" end="17602" sStart="17355" offset="240" sid="r9.fold.v.0989" wn="">As seen in Figure 9, both frameshift mutations lead to elimination of a highly conserved motif (NCVpRFaDT) near the carboxyl terminus of the peptide - a region that must be critical to proper function or folding.</s>
<s path="[OANC]/data/written_2/technical/biomed/gb-2001-2-6-research0021.anc" start="20367" end="20374" sStart="20206" offset="161" sid="r9.fold.v.0260" wn="">Both proteolytic cleavage (via MPP and/or IMP complexes) and chaperonin help (mt-HSP70/Ssc2p) in membrane trafficking and/or folding are needed for the mature frataxin protein to arrive at its destination in the matrix in its proper conformation.</s>
  
<s path="[OANC]/data/written_2/technical/biomed/gb-2002-3-11-research0059.anc" start="28188" end="28195" sStart="27960" offset="228" sid="r9.fold.v.0569" wn="">More than 75% (23/31) of the characterized genes within the top 50 genes in this cluster are localized to the ER and participate in various aspects of secretion, including protein folding ( KAR2, LHS1, FKB2, JEM1 ), protein disulfide isomerization ( EUG1, PDI1, ERO1 ), protein glycosylation ( GFA1, PMT3, PMI40, SEC59, WBP1, OST2 ), and forward and retrograde trafficking ( ERD2, ERP1, ERP2, SEC24, SEC13, RET2, RET3, and others [ 21]).</s>
<s path="[OANC]/data/written_2/technical/biomed/gb-2003-4-2-r11.anc" start="17240" end="17244" sStart="17195" offset="45" sid="r9.fold.v.0556" wn="">The prediction of a classical thiol-protease fold for the NlpC/P60 proteins also explains the circular permutation of the conserved motifs that is observed in several members of this superfamily such as LRAT and YaeF (Figure 1).</s>
  
<s path="[OANC]/data/written_2/technical/biomed/gb-2003-4-7-r42.anc" start="14934" end="14940" sStart="14695" offset="239" sid="r9.fold.v.0882" wn="">The rationale for defining 'regions' and 'super-regions' came from our observation that RNA folding algorithms would not necessarily identify characteristic pre-miRNA structures if they were folded within the context of longer RNAs, owing to base-pairing with non-miRNA sequence.</s>
  
<s path="[OANC]/data/written_2/technical/biomed/gb-2003-4-7-r42.anc" start="18652" end="18658" sStart="18602" offset="50" sid="r9.fold.v.0597" wn="">The top three mosquito hits were then folded and scored as before.</s>
<s path="[OANC]/data/written_2/technical/biomed/gb-2003-4-7-r42.anc" start="24417" end="24421" sStart="24290" offset="127" sid="r9.fold.v.0965" wn="">First, the mature miRNA can be derived from either arm of a given stem-loop, and many predicted pre-miRNAs fold well on either strand.</s>
<s path="[OANC]/data/written_2/technical/biomed/gb-2003-4-7-r42.anc" start="56857" end="56863" sStart="56824" offset="33" sid="r9.fold.v.0809" wn="">All Dm regions were folded with mfold 3.1 by submitting parallel batches of 500 mfolds to the cluster nodes and copying the .det and .out mfold output files to a final storage destination.</s>
<s path="[OANC]/data/written_2/technical/biomed/gb-2003-4-7-r42.anc" start="59373" end="59379" sStart="59309" offset="64" sid="r9.fold.v.0469" wn="">The blast hit was determined to be homologous if it folded into a similar structure as the drosophilid sequences and one or both helical arms were highly conserved; these candidates are flagged orange on the web output.</s>
<s path="[OANC]/data/written_2/technical/biomed/gb-2003-4-8-r51.anc" start="12034" end="12038" sStart="11968" offset="66" sid="r9.fold.v.0047" wn="">Finally, the SCOP classification of protein structures by fold (Figure 4a) and by family (Figure 4b) provides a convenient way to catalog the relative occurrences of structures in A. thaliana . With respect to folds, the membrane all-alpha fold, alpha-alpha superhelix and protein kinase-like (PK-like) fold ranked highest.</s>
<s path="[OANC]/data/written_2/technical/government/Media/FortWorthStarTelegram.anc" start="2580" end="2586" sStart="2475" offset="105" sid="r9.fold.v.0120" wn="">As part of a national overhaul of the Legal Services Corp., the nine legal aid groups in Texas are being folded into three, creating huge agencies handling cases in dozens of counties.</s>
  
<s path="[OANC]/data/written_2/travel_guides/berlitz2/Barcelona-WhereToGo.anc" start="3799" end="3805" sStart="3725" offset="74" sid="r9.fold.v.0276" wn="">When the vendors leave at the end of the day, their cage-lined stalls are folded and shut like wardrobes, with the birds rustling about inside.</s>
  
<s path="[OANC]/data/written_2/travel_guides/berlitz2/Cuba-WhereToGo.anc" start="60416" end="60422" sStart="60192" offset="224" sid="r9.fold.v.0358" wn="">Of the 61 skeletons on display, dating from 1490 to 1540 (more than 200 were disinterred), those in pre-conquest graves lie in a fetal position, while post-con-quest skeletons lie in a Christian pose: outstretched with arms folded.</s>
  
</list>
